### ISSUE TITLE
repo.spring.io no longer accessible

### ISSUE THREAD

**Issue by shugo83** [Prohelion/ArrowPoint-Telemetry#2]
Hi, Maven returns a 401 unauthorised error when attempting to access repo.spring.io. It seems that spring.io have altered their permissions. (https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020) 

Is there a workaround or alternative for resources such as https://repo.spring.io/libs-milestone/com/splunk/splunk/1.6.3.0/splunk-1.6.3.0.pom ?

Many thanks

**Comment by ctuesley** [comment]
Hi, thanks for raising this.  Not 100% sure at this stage what's happening here, been a while since I've built this code.  I'll have a look over the next couple of days and let you know.  If you have found a solution feel free to post it here and I can merge it in to the master branch.

**Comment by shugo83** [comment]
Changing the location of the splunk-artifactory in the `pom.xml` as below seems to have worked, but I have still got other issues so cannot confirm for certain. 

````
<repository>
	<id>splunk-artifactory</id>
	<name>Splunk Releases</name>
	<url>https://splunk.jfrog.io/splunk/ext-releases-local</url> 
</repository>
````

**Comment by shugo83** [comment]
Fully working with this change so closing this issue

**Comment by ctuesley** [comment]
For anyone who hits a similar issue the problem was due to a newer version of the JVM being used and incompatibilities  in the library versions used in this build.  If you are trying to build the product and having issues trying building the code with JVM8 or similar.
